//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReport.remote.TransactionsOperationsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="remote.TransactionsOperationsService.ITransactionsOperationsService")]
    public interface ITransactionsOperationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionsOperationsService/GetTransactionsByUserID", ReplyAction="http://tempuri.org/ITransactionsOperationsService/GetTransactionsByUserIDResponse" +
            "")]
        SpendingReport.Models.TransactionsModel GetTransactionsByUserID(int userId, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionsOperationsService/GetTransactionsByUserID", ReplyAction="http://tempuri.org/ITransactionsOperationsService/GetTransactionsByUserIDResponse" +
            "")]
        System.Threading.Tasks.Task<SpendingReport.Models.TransactionsModel> GetTransactionsByUserIDAsync(int userId, int skip, int take);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionsOperationsServiceChannel : SpendingReport.remote.TransactionsOperationsService.ITransactionsOperationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionsOperationsServiceClient : System.ServiceModel.ClientBase<SpendingReport.remote.TransactionsOperationsService.ITransactionsOperationsService>, SpendingReport.remote.TransactionsOperationsService.ITransactionsOperationsService {
        
        public TransactionsOperationsServiceClient() {
        }
        
        public TransactionsOperationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionsOperationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionsOperationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionsOperationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpendingReport.Models.TransactionsModel GetTransactionsByUserID(int userId, int skip, int take) {
            return base.Channel.GetTransactionsByUserID(userId, skip, take);
        }
        
        public System.Threading.Tasks.Task<SpendingReport.Models.TransactionsModel> GetTransactionsByUserIDAsync(int userId, int skip, int take) {
            return base.Channel.GetTransactionsByUserIDAsync(userId, skip, take);
        }
    }
}
