//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry()
        {
            this.TransactionCategories = new HashSet<TransactionCategory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> DateAvailable { get; set; }
        public Nullable<long> VariableSymbol { get; set; }
        public Nullable<short> ConstantSymbol { get; set; }
        public Nullable<long> SpecificSymbol { get; set; }
        public string Reference { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public int BankId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AmountInfoId { get; set; }
        public Nullable<int> SourceAccountId { get; set; }
        public Nullable<int> DestinationAccountId { get; set; }
    
        public virtual AmountInfo AmountInfo { get; set; }
        public virtual AmountInfo AmountInfo1 { get; set; }
        public virtual BankAccount SourceAccount { get; set; }
        public virtual BankAccount DestinationAccount { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCategory> TransactionCategories { get; set; }
    }
}
