//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public string Name { get; set; }
        public Nullable<int> CarId { get; set; }
        public string Description { get; set; }
        public Nullable<int> StationId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Fueling Fueling { get; set; }
        public virtual FuelStation FuelStation { get; set; }
    }
}
