//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public int Distance { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime Date { get; set; }
        public int CarId { get; set; }
        public Nullable<int> DistanceStart { get; set; }
        public Nullable<int> DistanceEnd { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
