//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity
{
    using System;
    
    public enum AmountType : sbyte
    {
        Credit = 0,
        Debit = 1,
        NotDefined = 2
    }
}
