//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmountInfo
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public int TypeId { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Type Type { get; set; }
    }
}
