//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingReportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public BankAccount()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int Id { get; set; }
        public Nullable<long> AccountNumber { get; set; }
        public string IBAN { get; set; }
        public string Name { get; set; }
        public Nullable<int> BankId { get; set; }
        public int UserId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
