//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spending_report.remote.TransactionDescriptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="remote.TransactionDescriptionService.ITransactionDescriptionService")]
    public interface ITransactionDescriptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionDescriptionService/AddTransactionDescription", ReplyAction="http://tempuri.org/ITransactionDescriptionService/AddTransactionDescriptionRespon" +
            "se")]
        bool AddTransactionDescription(SpendingReport.Models.TransactionDescription model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionDescriptionService/AddTransactionDescription", ReplyAction="http://tempuri.org/ITransactionDescriptionService/AddTransactionDescriptionRespon" +
            "se")]
        System.Threading.Tasks.Task<bool> AddTransactionDescriptionAsync(SpendingReport.Models.TransactionDescription model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionDescriptionServiceChannel : spending_report.remote.TransactionDescriptionService.ITransactionDescriptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionDescriptionServiceClient : System.ServiceModel.ClientBase<spending_report.remote.TransactionDescriptionService.ITransactionDescriptionService>, spending_report.remote.TransactionDescriptionService.ITransactionDescriptionService {
        
        public TransactionDescriptionServiceClient() {
        }
        
        public TransactionDescriptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionDescriptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionDescriptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionDescriptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddTransactionDescription(SpendingReport.Models.TransactionDescription model) {
            return base.Channel.AddTransactionDescription(model);
        }
        
        public System.Threading.Tasks.Task<bool> AddTransactionDescriptionAsync(SpendingReport.Models.TransactionDescription model) {
            return base.Channel.AddTransactionDescriptionAsync(model);
        }
    }
}
