// <auto-generated />
namespace SpendingReportEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class userID_manual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userID_manual));
        
        string IMigrationMetadata.Id
        {
            get { return "201501101521493_userID_manual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
